#!/bin/bash

# Displaying the help message
clear
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                     VitalWatch Help Guide                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Welcome to the VitalWatch Help Guide!"
echo "-------------------------------------------------------------"
echo ""
echo "About VitalWatch:"
echo "VitalWatch is a system monitoring tool designed to keep an eye on your"
echo "system's health and performance. It tracks metrics like CPU, Memory,"
echo "Disk usage, and more, helping you stay on top of your system's status."
echo ""
echo "-------------------------------------------------------------"
echo ""
echo "Installation Steps:"
echo "1. Download or clone the VitalWatch repository."
echo "2. Open a terminal, go in to the folder and run the installation script."
echo "   bash ./install.sh"
echo "3. After installation, you can access VitalWatch from your application"
echo "   menu or run it manually from the terminal."
echo ""
echo "To manually run VitalWatch, follow these steps:"
echo "1. Open a terminal."
echo "2. Activate the virtual environment:"
echo "   source ~/.vitalwatch/env/bin/activate"
echo "3. Run the application with:"
echo "   python ~/.vitalwatch/run.py"
echo ""
echo "-------------------------------------------------------------"
echo ""
echo "Uninstallation Steps:"
echo "1. To uninstall VitalWatch, run the uninstallation script:"
echo "   bash ./uninstall.sh"
echo "2. Follow the on-screen instructions to completely remove VitalWatch"
echo "   and all related files."
echo ""
echo "-------------------------------------------------------------"
echo ""
# echo "For more information or support, visit our official documentation."
echo ""
echo "Thank you for choosing VitalWatch to keep your system healthy!"
echo "Enjoy monitoring your system with ease!"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                   End of Help Guide                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
